### ISSUE TITLE
ENH: Add php quality tools as require-dev.

### ISSUE THREAD

**Issue by davidjeddy** [iranianpep/php-base-project#1]
Tools such as phpunit, phpcpd, phpmd, php-cs-fixer, a static analyzer, etc. Utility and tools that every project `should have` to help ensure a quality product.

**Comment by iranianpep** [comment]
Hey @davidjeddy 

Thanks for pointing this out.

[Codeclimate](https://codeclimate.com/github/iranianpep/php-base-project), [StyleCI](https://styleci.io/repos/88731011) and [Codacy](https://app.codacy.com/app/iranianpep/php-base-project) run all those checks as long as enable your repo in them. Obviously they're only free for public repos. I added `phpunit`, `phpcpd`, `phpmd` and `php_codesniffer` anyway in [1.0.6](https://github.com/iranianpep/php-base-project/releases/tag/1.0.6).

Cheers,
Ehsan
